### ISSUE TITLE
Script fails with 'NoneType' object has no attribute 'MakeLinkages'

### ISSUE THREAD

**Issue by sshearer** [TheSchnappi/articy2renpy#2]
Hi, I don't know if anyone is able to assist, but I'm getting the following error after exporting everything defined in my project.

Traceback (most recent call last):
  File "articy2renpy.py", line 208, in <module>
    TheGame.MakeLinkages(Episodes)
AttributeError: 'NoneType' object has no attribute 'MakeLinkages'

I assume it means I need to define something - but this points to the need for some error handling with specific recommendations.

Thanks,
Steven.

**Comment by TheSchnappi** [comment]
Hi Steven,

it seems that whatever you try to call, TheGame is not defined and therefore doesn't have a method named MakeLinkages().

Unfortunately I don't really get where the "TheGame.MakeLinkages(Episodes)" command/line comes from.
My script has nothing remotely named like this or uses custom classes - so my guess is that your error or script comes from somewhere else here.

**Comment by sshearer** [comment]
Thank you for the reply :).  I've also searched the main.py file for those keywords (& also NoneType) and not found them.  I did also search my JSON file for those keywords and they were not found there either !

I've since realized that I had not exported all objects (eg. neither Assets nor Documents).  After exporting everything and re-running, I now get a different error:

```
INFO:root:Step 1: Read Configuration File
INFO:root:Step 2: Read JSON File
INFO:root:Step 3: Store and Parse JSON Data
Traceback (most recent call last):
  File "C:\Users\T931768\Documents\My Family History\Britton-Mearsbeck Articy Project\main.py", line 267, in <module>
    dialogue_list.append(convert_dialogue(element))
  File "C:\Users\T931768\Documents\My Family History\Britton-Mearsbeck Articy Project\main.py", line 187, in convert_dialogue
    start_node = properties["InputPins"][0]["Connections"][0]["Target"]
KeyError: 'Connections'
```

I'm thinking it might be because (as a novice Articy user), I'd only defined Dialogs and Dialog Fragments (inside the Dialog) - ie. no Flow Fragments.  I think I need to review that portion of the course material to confirm my organization is correct.

**Comment by oistikbal** [comment]
@sshearer Hi, i get the same error, do you have any solution for the error?
